package net.m3mobile.feature.startup.constants

internal object TypeValue {

    const val GET_SERIAL_NUMBER = "get_serial"
    const val GET_WIFI_MAC = "get_wifi_mac"
    const val AIRPLANE = "airplane"
    const val INSTALL_APK = "apk_install"
    const val APPLICATION = "application"
    const val PERMISSION = "permission"
    const val DATETIME = "datetime"
    const val NTP = "ntp"
    const val TIMEZONE = "timezone"
    const val USB_SETTING = "usb_setting"
    const val CAPTIVE_PORTAL = "captive_portal"
    const val WIFI_FREQUENCY_BAND = "wifi_freq_band"
    const val WIFI_COUNTRY_CODE = "wifi_country_code"
    const val WIFI_OPEN_NOTIFICATION = "wifi_open_noti"
    const val VOLUME = "volume"
    const val WIFI_ROAMING_TRIGGER = "wifi_roam_trigger"
    const val WIFI_ROAMING_DELTA = "wifi_roam_delta"
    const val WIFI_SLEEP = "wifi_sleep"
    const val WIFI_STABILITY = "wifi_stability"
    const val WIFI_CHANNEL = "wifi_channel"
    const val APN = "apn"
    const val ACCESS_POINT = "access_point"
    const val CLEAR_WIFI = "remove_all_wifi"
    const val REMOVE_WIFI = "remove_wifi_by_ssid"
    const val DISPLAY = "display"
    const val QUICK_TILE = "quick_tile"
    const val OPTION = "option"
    const val LANGUAGE = "language"
    const val NFC = "nfc"
}